#!/usr/bin/env bash
# Generate production .env for VISHWAAS controller.
# Run once on the production machine; existing .env is not overwritten.
set -euo pipefail

ENV_FILE="$(dirname "$0")/.env"

if [ -f "$ENV_FILE" ]; then
  echo "ERROR: $ENV_FILE already exists. Edit it directly rather than regenerating."
  echo "       To start fresh: mv .env .env.bak && bash setup_prod_env.sh"
  exit 1
fi

# Require existing AGENT_TOKEN (already set manually on each node)
if [ -z "${VISHWAAS_AGENT_TOKEN:-}" ]; then
  echo "ERROR: Set VISHWAAS_AGENT_TOKEN in your shell before running this script."
  echo "       Example: export VISHWAAS_AGENT_TOKEN=\$(openssl rand -hex 32)"
  exit 1
fi

# Prompt for admin password
read -r -s -p "Enter admin dashboard password: " ADMIN_PW
echo
if [ -z "$ADMIN_PW" ]; then
  echo "ERROR: Password cannot be empty."
  exit 1
fi

read -r -p "Enter your dashboard domain (e.g. https://dashboard.example.com): " DOMAIN
if [ -z "$DOMAIN" ]; then
  echo "ERROR: Domain cannot be empty."
  exit 1
fi

JWT_SECRET=$(python3 -c "import secrets; print(secrets.token_hex(32))")
ADMIN_HASH=$(python3 -c "import bcrypt; print(bcrypt.hashpw(b'${ADMIN_PW}', bcrypt.gensalt()).decode())")

cat > "$ENV_FILE" <<EOF
# VISHWAAS Controller — Production Environment
# Generated by setup_prod_env.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

VISHWAAS_ENVIRONMENT=production
VISHWAAS_AGENT_TOKEN=${VISHWAAS_AGENT_TOKEN}
VISHWAAS_JWT_SECRET=${JWT_SECRET}
VISHWAAS_ADMIN_PASSWORD_HASH=${ADMIN_HASH}
VISHWAAS_ALLOWED_ORIGINS=${DOMAIN}

# Optional overrides
# VISHWAAS_DATABASE_URL=sqlite:///./vishwaas_master.db
# VISHWAAS_LOG_JSON=true
# VISHWAAS_JWT_EXPIRE_MINUTES=480
# VISHWAAS_LOG_RETENTION_DAYS=90
EOF

chmod 600 "$ENV_FILE"
echo ""
echo "✓ .env written to $ENV_FILE (mode 600)"
echo "✓ JWT secret generated"
echo "✓ Admin password hashed"
echo ""
echo "Next steps:"
echo "  1. Apply pending migrations:  cd controller/backend && .venv/bin/alembic upgrade head"
echo "  2. Configure nginx TLS:       sudo certbot --nginx -d <your-domain>"
echo "  3. Start in production mode:  cd controller && ./start_controller.sh --prod"
